# Build matrix
language: node_js
matrix:
  include:
    # Run lint only in Node.js 6.x
    - node_js: '6'
      env: LINT=true

    # Run tests in Node.js 4.x
    - node_js: '4'

    # Run tests in Node.js 5.x
    - node_js: '5'

    # Run tests in Node.js 6.x
    - node_js: '6'

    # Run tests in Node.js 8.x
    - node_js: '8'

  allow_failures:
    # Run tests in the latest version of Node.js
    - node_js: 'node'

# Build script
script: ./build-script

# Updates the dashboard after a successful deployment
after_success:
  - if [ $SNYK ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then snyk monitor --org=springernature; fi

# Build notifications
notifications:
  slack:
    secure: NOoWXmJOkn197lvsTMwnc4ACPfv6fnZuHg+y/WCT6rKVmCkyDWzcO8TGfvQUec7NkUGdH5Umeq4Ll0nDb2qxceMvEcAKaIsTxebO1AB2/ThOEM25yMi1h4ZpuMOTVPfMk8xqttJ9xOqkfgFtzczkbjYEFWMzGOX3KxjS6oOnScmbtdbB1yXbBMB75Ws0hehMEsNlRlD/76MSrlIwFHChSAUg/qJYA+mBEHOOnuMD9MbdfItmfPMu7ERxD3vrCnvE0hz++OongewofNloByTZAYBYq+OlkXvNK3Qd3H2kmhibwzVvxmo7YHOttsjXSFUUA0/URgwex/VOx75yO3D0FqJDC02w1GNQFSYGuMLnQQQI7G0CeqblBjg7Gya/YGcaASkxpsTVlOgy+K5ng5ZKtyAW7tY0YJlfpXTZEvouNlhntvhx9oa1N2hr+xrhzy3XLGa0qCsF4LSS5vQ6O9oimW02XS8LiSdyerL23F/wrm2wOizAUwV3OpNEMH5UAan1C4mlVnoNQZaVskjucxYqRDGjdxx0M8SwLBrKrh8PqURXdktjTuzj8jtMtqsMHeTswcb+IS7RrfQB1hs5EX6pEw/3RMASYsUT4Q4yo+Lc5ReU2bdvS468uQEH87MBhwqOqdjACpu+zgzBag8O9RF+BqHcutgLFpgY3yFz0TOEcQo=
