# Build matrix
language: node_js
matrix:
  include:
    # Run lint only in Node.js 6.x
    - node_js: '6'
      env: LINT=true

    # Run tests in Node.js 6.x
    - node_js: '6'

    # Run tests in Node.js 4.x
    - node_js: '4'

# Dependencies require GCC 4.8
env:
  global:
    CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'if [ $LINT ]; then make lint; fi'
  - 'if [ ! $LINT ]; then make lcov-levels; fi'
  #- 'if [ ! $LINT ]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi'
