
# Build matrix
language: node_js
matrix:
  include:

    # Lint only in Node.js 0.10
    - node_js: '0.10'
      env: LINT=true

    # Run tests in Node.js 0.10
    - node_js: '0.10'

    # Run tests in Node.js 0.12
    - node_js: '0.12'

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'if [ $LINT ]; then make lint; fi'
  - 'if [ ! $LINT ]; then make lcov-levels; fi'
